### ISSUE TITLE
Commit a88f6b23f62c broke the `python3 setup.py install && py.test` workflow

### ISSUE THREAD

**Issue by lpechacek** [pyproj4/pyproj#647]
#### Installation method/steps
I'm packaging pyproj for openSUSE project. The build and installation steps boil down to `python3 setup.py install` and `py.test`. Example build log can be found at https://build.opensuse.org/package/live_build_log/Application:Geo/python-pyproj/openSUSE_Tumbleweed/x86_64. Until v2.6.0 this installation procedure worked fine. Trying to upgrade to v2.6.1 resulted in tests failing to start. The corresponding log part is:
```
...
[   17s] + py.test-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v
[   17s] ImportError while loading conftest '/home/abuild/rpmbuild/BUILD/pyproj-2.6.1.post1/test/conftest.py'.
[   17s] test/conftest.py:4: in <module>
[   17s]     from pyproj.datadir import get_data_dir
[   17s] pyproj/__init__.py:50: in <module>
[   17s]     from pyproj import _datadir
[   17s] E   ImportError: cannot import name '_datadir' from partially initialized module 'pyproj' (most likely due to a circular import) (/home/abuild/rpmbuild/BUILD/pyproj-2.6.1.post1/pyproj/__init__.py)
[   17s] error: Bad exit status from /var/tmp/rpm-tmp.BRrH1g (%check)
...
```

Git bisect led to commit a88f6b23f62c ("TST: Update tests with behavior with new PROJ grids (#594)"). How to fix pyproj so that the above build procedure completes again, please?

#### Environment Information
 - pyproj v2.6.1rel
 - PROJ 7.0.0
 - Python 3.8.2
 - Operation System Linux-5.6.11-1-default-x86_64-with-glibc2.2.5 (openSUSE Tumbleweed - rolling distro)

**Comment by snowman2** [comment]
It seems it is attempting to access the local files that don't exist in your `pyproj` directory since they were not built there. To resolve this, one option would be to move the `test` folder to another directory to run tests from. This will ensure the correct pyproj files are imported.

**Comment by snowman2** [comment]
We do this when building/testing wheels: https://github.com/pyproj4/pyproj-wheels/blob/3399397ad58394f3c40a0e9d69d36714201c5fce/config.sh#L70-L78

**Comment by lpechacek** [comment]
Thanks, Alan, for your assistance. Your comments helped me look in the right direction. The package is now [building fine](https://build.opensuse.org/package/show/Application:Geo/python-pyproj) in openSUSE Build Service.

In the end, the solution was to download v2.6.1.post1 from PyPi, which also fixes the manifest. The isolation of local files, which you suggested, is already happening in the build, so the package built right away after adding `python-testsuite` to the mix. The rest was my lack of experience with the test suite and inability to efficiently diagnose the problems found. The issue is closed on my side. Thanks!

**Comment by snowman2** [comment]
Glad to hear that you have it figured out 👍
